name: Raspberry Pi Camera Tests

# Trigger the workflow on push to any branch, pull requests to any branch, and manual triggers
on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Python Installation
        run: |
          python3.11 --version
          pip3.11 --version

      - name: Install Dependencies
        run: |
          python3.11 -m pip install --upgrade pip
          sudo apt install python3 python3-pillow

      - name: Run Test Suite
        run: |
          python3.11 testing/main.py

      - name: Upload Testing Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testing-report
          path: testing_report.txt
