name: New Comprehensive Test

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Python Installation
        run: |
          python3 --version

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pillow meson ninja-build

      - name: Setup Meson Build Directory
        run: |
          meson setup build

      - name: Build Project
        run: |
          meson compile -C build

      - name: Run Test Suite
        run: |
          python3 testing/main.py

      - name: Upload Testing Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testing-report
          path: testing_report.txt
