name: Sync to Bitbucket

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Push to Bitbucket
      env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
      run: |
        git remote add bitbucket https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@bitbucket.org/comp3888-p05a/p05a-rpicam-apps.git
        git push bitbucket --all --force
        git push bitbucket --tags
